In [1]:
### Project Overview
# This projects seeks to answer the research question...
# Can text analysis of Indeed job listing descriptions identify recurring and role-specific skills and phrases useful 
# for resume tailoring?

In [2]:
import re

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from datasets import load_dataset
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [3]:
### Experiment 1:
# Evaluate descriptions 1 for keywords using BOW
# Evaluate TF-IDF for descriptions 1 breaking documents by sentence

dataset = load_dataset("burcuonel/datajob_indeed_usa")

df = dataset["train"].to_pandas()

df['Descriptions'].head()

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

0    We invite you to join us at Driven Brands!\nHe...
1    Sabot Consulting (Sabot) is a management consu...
2    Job Details\nApply\nSave\nPrint this job\nEmai...
3    Position: Data Engineer\nLocation: MN\nAs a Da...
4    Full Job Description\nThe Network Administrato...
Name: Descriptions, dtype: str

In [4]:
# Explore description 1 for structure
description = df["Descriptions"].iloc[0]

# Split expression segments based on whitespace following characters (. , ! ?)
segments = re.split(r"(?<=[.!?])\s+|\n+", description)

segment = [segment.strip() for segment in segments if segment.strip()]

for index, segment in enumerate(segments):
    print(f'{index}: {segment}\n')

0: We invite you to join us at Driven Brands!

1: Headquartered in Charlotte, NC, Driven Brands (NASDAQ: DRVN) is the largest automotive services company in North America, providing a range of consumer and commercial automotive needs, including paint, collision, glass, vehicle repair, oil change, maintenance and car wash.

2: With over 4,500 centers in 15 countries, Driven Brands is the parent company of some of North America’s leading automotive service brands including Take 5 Oil Change, Take 5 Car Wash, Driven Glass, Meineke, Maaco, CARSTAR, and more.

3: Our network services over 50 million vehicles annually and generates more than $5 billion in system-wide sales each year.

4: Our culture inspires high performance and innovation, enabling our employees to go further, faster in their careers.

5: With amazing people and great brands, we confidently look forward to exciting growth ahead, and believe in following the values that support this vision.

6: JOB DESCRIPTION:

7: This is a highly impactful and autonomous role where your contribution will be noticed on day one.

8: You’ll be working alongside a team of eight analysts & data scientists - collaborating to design datasets, develop analytical models & provide insights.

9: Your work will impact business processes and drive growth.

10: Responsibilities:

11: Partner with stakeholders across departments to translate business needs and define technical requirements

12: Identify, analyze & interpret trends in complex, unfamiliar datasets across our brands

13: Build dashboards & reports for audiences with varying levels of technical context, optimizing strategic decision-making throughout the company

14: Develop & maintain scalable automations for data sources, reports, periodic analysis

15: Assist Data Science team in discovery, back-end dev, optimization of advanced analytics models

16: Qualifications:

17: Bachelor’s degree in a quantitative field (math, statistics, physics, engineering, economics, computer science) or equivalent years of experience

18: Experience in SQL & a scripting language (R/Python)

19: Advanced degree in a quantitative field

20: 1-2 years of professional experience in data analysis or a related field

21: Strong proficiency in querying & manipulating large datasets using SQL

22: Experience performing data analysis and/or building automations & statistical models in Python/R

23: Experience in data visualization, preferably in Tableau, Qlik or Power BI

24: Strong interpersonal & teamwork skills, capable of inter-departmental collaboration

25: #LI-KD1

26: #HYBRID

27: DBCORP

In [5]:
# Create unigram BOW for description 1
bow_vectorizer = CountVectorizer(
    analyzer="word", ngram_range=(1, 1), stop_words="english"
)

bow_matrix = bow_vectorizer.fit_transform([description])

print(bow_matrix.shape)

# Create labeled table of BOW counts, gathering results for top 15 unigrams
bow_results = pd.DataFrame(
    {"token": bow_vectorizer.get_feature_names_out(), "count": bow_matrix.toarray()[0]}
)

top_n = 15

bow_results.sort_values("count", ascending=False).head(top_n)

(1, 188)

            token  count
23         brands      6
48           data      6
72     experience      5
63         driven      4
38        company      3
49       datasets      3
17     automotive      3
8        analysis      3
115        models      3
74          field      3
16    automations      2
32         change      2
54         degree      2
154       science      2
143  quantitative      2

In [6]:
# Create BOW for description 1 based on unigram
bow_vectorizer = CountVectorizer(
    analyzer="word", ngram_range=(2, 2), stop_words="english"
)

bow_matrix = bow_vectorizer.fit_transform([description])

print(bow_matrix.shape)

# Create labeled table of BOW counts, gathering results for top 15 unigrams
bow_results = pd.DataFrame(
    {"token": bow_vectorizer.get_feature_names_out(), "count": bow_matrix.toarray()[0]}
)

bow_results.sort_values("count", ascending=False).head(top_n)

(1, 231)

                   token  count
84         driven brands      3
94       experience data      2
63         data analysis      2
53         company north      2
74   degree quantitative      2
41              car wash      2
153        north america      2
155           oil change      2
177   quantitative field      2
7         amazing people      1
10       analysis assist      1
11     analysis building      1
8        america leading      1
9      america providing      1
14     analytical models      1

In [7]:
# Apply TF-IDF across description 1 segments
tfidf_vectorizer = TfidfVectorizer(stop_words="english")

tfidf_matrix = tfidf_vectorizer.fit_transform(segments)

print(tfidf_matrix.shape)

# Create labeled table of TF-IDF tokens
tfidf_table = pd.DataFrame(
    tfidf_matrix.toarray(), columns=tfidf_vectorizer.get_feature_names_out()
)

# Compare each segment with its highest weighted tokens
for index, segment in enumerate(segments):
    scores = tfidf_table.iloc[index]

    top_tokens = (
        scores[scores > 0]
        .sort_values(ascending=False)
        .head(5)
    )

    print(f'Segment {index}: {segment}')
    print(top_tokens)
    print()

(28, 188)
Segment 0: We invite you to join us at Driven Brands!
join      0.563466
invite    0.563466
driven    0.457165
brands    0.394983
Name: 0, dtype: float64

Segment 1: Headquartered in Charlotte, NC, Driven Brands (NASDAQ: DRVN) is the largest automotive services company in North America, providing a range of consumer and commercial automotive needs, including paint, collision, glass, vehicle repair, oil change, maintenance and car wash.
automotive    0.336925
consumer      0.189360
commercial    0.189360
collision     0.189360
charlotte     0.189360
Name: 1, dtype: float64

Segment 2: With over 4,500 centers in 15 countries, Driven Brands is the parent company of some of North America’s leading automotive service brands including Take 5 Oil Change, Take 5 Car Wash, Driven Glass, Meineke, Maaco, CARSTAR, and more.
driven       0.343008
brands       0.296353
500          0.211382
countries    0.211382
carstar      0.211382
Name: 2, dtype: float64

Segment 3: Our network services over 50 million vehicles annually and generates more than $5 billion in system-wide sales each year.
50           0.304411
annually     0.304411
billion      0.304411
generates    0.304411
million      0.304411
Name: 3, dtype: float64

Segment 4: Our culture inspires high performance and innovation, enabling our employees to go further, faster in their careers.
careers      0.333333
culture      0.333333
employees    0.333333
enabling     0.333333
faster       0.333333
Name: 4, dtype: float64

Segment 5: With amazing people and great brands, we confidently look forward to exciting growth ahead, and believe in following the values that support this vision.
ahead          0.264602
amazing        0.264602
believe        0.264602
confidently    0.264602
exciting       0.264602
Name: 5, dtype: float64

Segment 6: JOB DESCRIPTION:
description    0.707107
job            0.707107
Name: 6, dtype: float64

Segment 7: This is a highly impactful and autonomous role where your contribution will be noticed on day one.
autonomous      0.377964
contribution    0.377964
day             0.377964
highly          0.377964
impactful       0.377964
Name: 7, dtype: float64

Segment 8: You’ll be working alongside a team of eight analysts & data scientists - collaborating to design datasets, develop analytical models & provide insights.
alongside        0.273856
analysts         0.273856
analytical       0.273856
collaborating    0.273856
design           0.273856
Name: 8, dtype: float64

Segment 9: Your work will impact business processes and drive growth.
drive        0.423223
impact       0.423223
work         0.423223
processes    0.423223
business     0.376517
Name: 9, dtype: float64

Segment 10: Responsibilities:
responsibilities    1.0
Name: 10, dtype: float64

Segment 11: Partner with stakeholders across departments to translate business needs and define technical requirements
define          0.34556
translate       0.34556
departments     0.34556
partner         0.34556
requirements    0.34556
Name: 11, dtype: float64

Segment 12: Identify, analyze & interpret trends in complex, unfamiliar datasets across our brands
analyze      0.373988
complex      0.373988
interpret    0.373988
identify     0.373988
trends       0.373988
Name: 12, dtype: float64

Segment 13: Build dashboards & reports for audiences with varying levels of technical context, optimizing strategic decision-making throughout the company
audiences     0.285817
build         0.285817
context       0.285817
dashboards    0.285817
decision      0.285817
Name: 13, dtype: float64

Segment 14: Develop & maintain scalable automations for data sources, reports, periodic analysis
maintain       0.365954
scalable       0.365954
sources        0.365954
periodic       0.365954
automations    0.325569
Name: 14, dtype: float64

Segment 15: Assist Data Science team in discovery, back-end dev, optimization of advanced analytics models
analytics    0.325008
assist       0.325008
dev          0.325008
end          0.325008
discovery    0.325008
Name: 15, dtype: float64

Segment 16: Qualifications:
qualifications    1.0
Name: 16, dtype: float64

Segment 17: Bachelor’s degree in a quantitative field (math, statistics, physics, engineering, economics, computer science) or equivalent years of experience
bachelor       0.284953
computer       0.284953
economics      0.284953
engineering    0.284953
equivalent     0.284953
Name: 17, dtype: float64

Segment 18: Experience in SQL & a scripting language (R/Python)
language      0.495419
scripting     0.495419
python        0.440746
sql           0.440746
experience    0.347283
Name: 18, dtype: float64

Segment 19: Advanced degree in a quantitative field
advanced        0.510861
degree          0.510861
quantitative    0.510861
field           0.465900
Name: 19, dtype: float64

Segment 20: 1-2 years of professional experience in data analysis or a related field
professional    0.445712
related         0.445712
years           0.396525
analysis        0.361626
field           0.361626
Name: 20, dtype: float64

Segment 21: Strong proficiency in querying & manipulating large datasets using SQL
large           0.371616
manipulating    0.371616
proficiency     0.371616
querying        0.371616
using           0.371616
Name: 21, dtype: float64

Segment 22: Experience performing data analysis and/or building automations & statistical models in Python/R
building       0.382774
statistical    0.382774
performing     0.382774
python         0.340532
automations    0.340532
Name: 22, dtype: float64

Segment 23: Experience in data visualization, preferably in Tableau, Qlik or Power BI
bi            0.379986
power         0.379986
qlik          0.379986
preferably    0.379986
tableau       0.379986
Name: 23, dtype: float64

Segment 24: Strong interpersonal & teamwork skills, capable of inter-departmental collaboration
capable          0.358253
collaboration    0.358253
departmental     0.358253
inter            0.358253
interpersonal    0.358253
Name: 24, dtype: float64

Segment 25: #LI-KD1
kd1    0.707107
li     0.707107
Name: 25, dtype: float64

Segment 26: #HYBRID
hybrid    1.0
Name: 26, dtype: float64

Segment 27: DBCORP
dbcorp    1.0
Name: 27, dtype: float64

In [ ]:
### Experiment 1 results
# The BOW model for description 1 yielded very little progress in favor of extracting useful keywords from a singular job description
# Unigrams appeared to contain less meaningful language than bigrams with english stop words, results without stop words were unusable
# TF-IDF at the sentence level also failed to isolate meaningful keywords that could be interpreted as leading terms

### Interpretation 
# These results provide a useful baseline for further study, but fail to prove that this singular job description surfaces ats-target keywords 
# based solely on frequency, or that a meaningful association exists between a keyword and description language

In [9]:
### Experiment 2
# Evaluate BOW model for keywords, short phrases across all descriptions
# Assess TF-IDF across all descriptions

descriptions = df['Descriptions'].dropna()
descriptions = descriptions[descriptions.str.strip().ne("")]

print(f'Documents: {len(descriptions)}')

Documents: 1200

In [10]:
# Create unigram BOW using all descriptions
unigram_vectorizer = CountVectorizer(
    analyzer="word", ngram_range=(1, 1), stop_words="english"
)

unigram_matrix = unigram_vectorizer.fit_transform(descriptions)

print(unigram_matrix.shape)

# Create counts for unigrams found in the documents
total_counts = unigram_matrix.sum(axis=0).A1
document_counts = (unigram_matrix > 0).sum(axis=0).A1

# Develop table for unigram stats
unigram_results = pd.DataFrame(
    {
        "token": unigram_vectorizer.get_feature_names_out(),
        "total_count": total_counts,
        "document_count": document_counts,
    }
)

# Find percent of documents the unigrams appear in
unigram_results["document_pct"] = (
    unigram_results["document_count"] / len(descriptions) * 100
)

top_n = 20

unigram_results.sort_values("total_count", ascending=False).head(top_n)

(1200, 14731)

              token  total_count  document_count  document_pct
4117           data        10183            1078     89.833333
5594     experience         6821            1140     95.000000
2649       business         4251             902     75.166667
14579          work         3757            1105     92.083333
13252          team         3125             914     76.166667
14682         years         2301             930     77.500000
12009       science         2219             743     61.916667
12425        skills         2156             900     75.000000
8082       learning         2035             589     49.083333
4485    development         1871             769     64.083333
11514      required         1774             695     57.916667
1046        ability         1687             738     61.500000
7751            job         1684             880     73.333333
1582      analytics         1658             515     42.916667
12546     solutions         1640             668     55.666667
13476          time         1598             776     64.666667
4121       database         1555             360     30.000000
13070       support         1525             666     55.500000
11517  requirements         1500             689     57.416667
13267     technical         1494             668     55.666667

In [15]:
# Explore bigram and trigram BOW using all descriptions without stop words
bigram_vectorizer = CountVectorizer(
    analyzer="word", ngram_range=(2, 2), stop_words="english"
)

bigram_matrix = bigram_vectorizer.fit_transform(descriptions)

print(bigram_matrix.shape)

# Create counts for bigrams found in the documents
total_counts = bigram_matrix.sum(axis=0).A1
document_counts = (bigram_matrix > 0).sum(axis=0).A1

# Develop table for bigram stats
bigram_results = pd.DataFrame(
    {
        "token": bigram_vectorizer.get_feature_names_out(),
        "total_count": total_counts,
        "document_count": document_counts,
    }
)

# Find percent of documents the unigrams appear in
bigram_results["document_pct"] = (
    bigram_results["document_count"] / len(descriptions) * 100
)

top_n = 30

bigram_results.sort_values("total_count", ascending=False).head(top_n)

(1200, 185462)

                        token  total_count  document_count  document_pct
98690        machine learning         1461             480     40.000000
42165            data science         1414             453     37.750000
185051       years experience          755             451     37.583333
34120        computer science          556             475     39.583333
22656   business intelligence          449             207     17.250000
41311          data analytics          442             233     19.416667
17430         bachelor degree          429             385     32.083333
65032      experience working          426             297     24.750000
60993       equal opportunity          406             363     30.250000
182613          work location          405             398     33.166667
31752    communication skills          397             359     29.916667
90118                job type          376             361     30.083333
152754     sexual orientation          376             369     30.750000
108976        national origin          368             360     30.000000
42171         data scientists          346             234     19.500000
72610         gender identity          325             318     26.500000
114551   opportunity employer          321             297     24.750000
179335         veteran status          315             308     25.666667
166543           team members          313             230     19.166667
64156         experience data          310             249     20.750000
139033          related field          298             264     22.000000
185165         years required          296             102      8.500000
78943              hour shift          295             290     24.166667
148232          schedule hour          289             286     23.833333
158041             sql server          288             148     12.333333
136162             race color          284             278     23.166667
89957         job description          280             242     20.166667
97729         location remote          277             246     20.500000
41306           data analysis          275             205     17.083333
19594          best practices          265             221     18.416667

In [28]:
# Apply TF-IDF across Descriptions feature assessing bigrams
tfidf_vectorizer = TfidfVectorizer(stop_words="english", ngram_range=(2, 2))

tfidf_matrix = tfidf_vectorizer.fit_transform(descriptions)
print(tfidf_matrix.shape)

# Assess bigram appearance in a single description
feature_names = tfidf_vectorizer.get_feature_names_out()

first_description_scores = pd.DataFrame(
    {"bigram": feature_names, "tfidf": tfidf_matrix[0].toarray().ravel()}
)

first_description_scores.query("tfidf > 0").sort_values('tfidf').head(top_n)

(1200, 185462)

                         bigram     tfidf
34120          computer science  0.018476
42165              data science  0.018930
185051         years experience  0.018972
17430           bachelor degree  0.020487
139033            related field  0.024096
89957           job description  0.024927
42171           data scientists  0.025248
42204              data sources  0.029429
43959           decision making  0.029816
42357        data visualization  0.029948
22731            business needs  0.030082
134968  qualifications bachelor  0.033351
148972             science team  0.033543
64884            experience sql  0.033839
68176               field years  0.034783
22796        business processes  0.034894
125478                 power bi  0.035120
64292     experience experience  0.035351
7075         advanced analytics  0.035709
77849          high performance  0.038348
130658  professional experience  0.039010
172940       translate business  0.039359
157917           sql experience  0.040098
7102            advanced degree  0.040692
177300                using sql  0.040898
48143          develop maintain  0.041324
159827       statistical models  0.042002
134652        python experience  0.042239
92474            large datasets  0.042731
161576     strong interpersonal  0.042987